### ISSUE TITLE
Difficulty running for first time

### ISSUE THREAD

**Issue by benquan** [petergardfjall/garminexport#10]
I am testing garminbackup.py for first time but getting these errors

What I am really interested in is using upload_activity.py to automate the load of a fit file. But I guess I have to make garminbackup.py work first.

Any help would be appreciated!

Test:
(venv.garminexport) Bens-MacBook-Air:garminexport ben$ ./garminbackup.py --backup-dir=activities yyy@gmail.com
2016-11-03 04:33:46,685 [INFO] backing up formats: json_summary, json_details, gpx, tcx, fit
Enter password: 
2016-11-03 04:33:55,714 [INFO] authenticating user ...
2016-11-03 04:34:00,953 [INFO] retrieving activities for yyy@gmail.com ...
2016-11-03 04:34:03,088 [INFO] account has a total of 38 activities.
2016-11-03 04:34:03,089 [INFO] activities contains 0 backed up activities.
2016-11-03 04:34:03,089 [INFO] activities that aren't backed up: 38
2016-11-03 04:34:03,090 [INFO] backing up activity 1422175922 from 2016-10-26 17:56:00+00:00 (1 out of 38) ...
2016-11-03 04:34:03,269 [ERROR] failed with exception: failed to fetch activity 1422175922: 410
The requested endpoint is retired
2016-11-03 04:34:03,276 [ERROR] failed with exception: failed to fetch activity 1422175922: 410
The requested endpoint is retired
Traceback (most recent call last):
  File "./garminbackup.py", line 102, in <module>
    client, activity, args.backup_dir, args.format)
  File "/Users/ben/venv.garminexport/src/garminexport/garminexport/backup.py", line 118, in download
    activity_summary = client.get_activity_summary(id)
  File "/Users/ben/venv.garminexport/src/garminexport/garminexport/garminclient.py", line 52, in check_session
    return client_function(*args, **kwargs)        
  File "/Users/ben/venv.garminexport/src/garminexport/garminexport/garminclient.py", line 271, in get_activity_summary
    activity_id, response.status_code, response.text))
Exception: failed to fetch activity 1422175922: 410
The requested endpoint is retired

**Comment by petergardfjall** [comment]
I'm aware of this issue but I haven't really come to a decision on how to move forward.

It seems like Garmin has shut down the endpoint serving (what I refer to as) "json summary" data about an activity. It used to be served at `https://connect.garmin.com/modern/proxy/activity-service-1.3/json/activity/<id>` (try this while logged in at Garmin Connect with an activity id of yours -- typically a 10-digit numer like `1356850337`) and you will see an error message saying 

```
The requested endpoint is retired
```

The API of the activity-service-1.3 can be viewed [here](https://connect.garmin.com/modern/proxy/activity-service-1.3/index.html) (*note: you need to be logged in at Garmin Connect to view it).

I'm kind of leaning towards either replacing the "json summary" with a call to a different endpoint.
Either `https://connect.garmin.com/modern/proxy/activity-service-1.3/json/activity_embed/<activityId>`, which appears to be producing similar data or `https://connect.garmin.com/modern/proxy/activity-service/activity/<activityId>`, which produces a lot less data (try them out and see for yourself). I'm open for ideas. It would break backwards compatability, since new "json summary" files would have a different format. However, I'm not sure to what extent people are interested in that format. Myself, I can do without it completely.

For your case, a workaround would be to run without requesting "json summary" files.
That is, use `-f` flags to specify which formats to download: `-f json_details -f gpx -f tcx -f fit`.

Alternatively, you could try running with `--ignore-errors`.

**Comment by petergardfjall** [comment]
@dlenski: do you have opinions/ideas regarding how to move forward on https://github.com/petergardfjall/garminexport/issues/10#issuecomment-258248879

**Comment by dlenski** [comment]
@petergardfjall, looks like the first endpoint is very similar indeed to the old version and is probably the logical replacement.

Unfortunately, I don't have any saved copies of the old "json summary" handy… are there any differences at all between the two?

**Comment by petergardfjall** [comment]
@dlenski: I couldn't find any significant differences. 

I replaced the old endpoint `https://connect.garmin.com/modern/proxy/activity-service-1.3/json/activity/<id>` with `https://connect.garmin.com/modern/proxy/activity-service-1.3/json/activity_embed/<activityId>`.
