### ISSUE TITLE
unable to extract flowExecutionKey

### ISSUE THREAD

**Issue by JeanDiv14** [petergardfjall/garminexport#13]
Good Morning Peter

I started picking up a fairly lengthly error this morning.. mostly HTML code, but it started off with this:

> [ERROR] failed with exception: auth failure: unable to extract flowExecutionKey: https://sso.garmin.com/sso/login:

It then ended after the html with:

> Traceback (most recent call last):
  File "/garminexport/./garminbackup.py", line 80, in <module>
    with GarminClient(args.username, args.password) as client:
  File "/garminexport/garminexport/garminclient.py", line 87, in __enter__
    self.connect()
  File "/garminexport/garminexport/garminclient.py", line 95, in connect
    self._authenticate()
  File "/garminexport/garminexport/garminclient.py", line 109, in _authenticate
    flow_execution_key = self._get_flow_execution_key(params)
  File "/garminexport/garminexport/garminclient.py", line 138, in _get_flow_execution_key
    (SSO_LOGIN_URL, response.text))
RuntimeError

I hope thats helpful..?

Ta,
Jean

**Comment by petergardfjall** [comment]
Thanks for reporting. Could you try with the latest version.
Commit https://github.com/petergardfjall/garminexport/commit/93d27057dca0e43a38bfc0fc005d00e2b201509e seems to have fixed this on my end.

**Comment by JeanDiv14** [comment]
Success!

Again, thank you. This little piece of software makes my life easier on a DAILY basis, and I really appreciate it :-)
