### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by tymmej** [petergardfjall/garminexport#29]
Script uses 100% of one CPU.

By pressing ctrl+c few times traceback always shows something like that:

```
Traceback (most recent call last):                                                                                                                
  File "C:\Users\Jakub Tymejczyk\Documents\garminexport\garminbackup.py", line 117, in <module>                                                   
    args.format)                                                                                                                                  
  File "C:\Users\Jakub Tymejczyk\Documents\garminexport\garminexport\backup.py", line 145, in download                                            
    activity_gpx = retryer.call(client.get_activity_gpx, id)                                                                                      
  File "C:\Users\Jakub Tymejczyk\Documents\garminexport\garminexport\retryer.py", line 204, in call                                               
    returnval = function(*args, **kw)                                                                                                             
  File "C:\Users\Jakub Tymejczyk\Documents\garminexport\garminexport\garminclient.py", line 53, in check_session                                  
    return client_function(*args, **kwargs)                                                                                                       
  File "C:\Users\Jakub Tymejczyk\Documents\garminexport\garminexport\garminclient.py", line 284, in get_activity_gpx                              
    return response.text                                                                                                                          
  File "C:\Users\Jakub Tymejczyk\Documents\garminexport\venv\lib\site-packages\requests\models.py", line 769, in text                             
    encoding = self.apparent_encoding                                                                                                             
  File "C:\Users\Jakub Tymejczyk\Documents\garminexport\venv\lib\site-packages\requests\models.py", line 643, in apparent_encoding                
    return chardet.detect(self.content)['encoding']                                                                                               
  File "C:\Users\Jakub Tymejczyk\Documents\garminexport\venv\lib\site-packages\requests\packages\chardet\__init__.py", line 30, in detect         
    u.feed(aBuf)                                                                                                                                  
  File "C:\Users\Jakub Tymejczyk\Documents\garminexport\venv\lib\site-packages\requests\packages\chardet\universaldetector.py", line 128, in feed 
    if prober.feed(aBuf) == constants.eFoundIt:                                                                                                   
  File "C:\Users\Jakub Tymejczyk\Documents\garminexport\venv\lib\site-packages\requests\packages\chardet\charsetgroupprober.py", line 64, in feed 
    st = prober.feed(aBuf)                                                                                                                        
  File "C:\Users\Jakub Tymejczyk\Documents\garminexport\venv\lib\site-packages\requests\packages\chardet\mbcharsetprober.py", line 56, in feed    
    codingState = self._mCodingSM.next_state(aBuf[i])                                                                                             
  File "C:\Users\Jakub Tymejczyk\Documents\garminexport\venv\lib\site-packages\requests\packages\chardet\codingstatemachine.py", line 54, in next_
state                                                                                                                                             
    self._mCurrentBytePos += 1                            
KeyboardInterrupt                                                                                        
```

CPU is used by `apparent_encoding` which tries to detect encoding of file.
I added one extra `print` to see which encoding is detected: always UTF-8.

Replacing `return chardet.detect(self.content)['encoding']` with return 'UTF-8' reduces CPU usage to <1%.

Is it any solution to this problem without modyfing `requests` module?

**Comment by petergardfjall** [comment]
I have no idea. Feel free to investigate. Is the same behavior seen with a more recent version of the requests library?

**Comment by cwygoda** [comment]
I don't see this behavior, but you're on Windows. If I would investigate,  I would benchmark chardet on Windows vs Linux, I have a hunch this may only be slow on Windows.
To avoid requests guessing the encoding, one must set the encoding on the response object before accessing the text attribute: https://github.com/kennethreitz/requests/blob/bedd9284c9646e50c10b3defdf519d4ba479e2c7/requests/models.py#L856
