### ISSUE TITLE
.Fit file failure 

### ISSUE THREAD

**Issue by JeanDiv14** [petergardfjall/garminexport#8]
Hey Peter

Picking up errors again, output below.

Do Garmin keep changing specifically to stop this kind of access, or is it just 'normal' development that is messing with how your software pulls the files?

Thanks again for the hard work.
Jean

2016-09-17 11:12:14,314 [INFO] backing up formats: fit
2016-09-17 11:12:14,317 [INFO] authenticating user ...
2016-09-17 11:12:16,311 [ERROR] failed with exception: Failed to parse: http:\
Traceback (most recent call last):
  File "/root/garminexport3/./garminbackup.py", line 80, in <module>
    with GarminClient(args.username, args.password) as client:
  File "/root/garminexport3/garminexport/garminclient.py", line 87, in __enter__
    self.connect()
  File "/root/garminexport3/garminexport/garminclient.py", line 95, in connect
    self._authenticate()
  File "/root/garminexport3/garminexport/garminclient.py", line 113, in _authenticate
    self._validate_auth_ticket(validation_url)
  File "/root/garminexport3/garminexport/garminclient.py", line 165, in _validate_auth_ticket
    response = self.session.get(validation_url, allow_redirects=False)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 469, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 443, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 374, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 304, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 354, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/util/url.py", line 143, in parse_url
    raise LocationParseError(url)
requests.packages.urllib3.exceptions.LocationParseError: Failed to parse: http:\

**Comment by petergardfjall** [comment]
Right! Seems as though Garmin started escaping slashes with backslashes in the validation ticket URL, which confused the HTTP client library. 

Please pull the latest commit and see if that takes care of the problem. It did for me.

**Comment by JeanDiv14** [comment]
Hey Peter

Success!

Thanks again..
